import "./globals.css";
import { Inter } from "next/font/google";
import ReactQueryClient from "./components/useClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MovieDB App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClient>
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">{children}</div>
        </ReactQueryClient>
      </body>
    </html>
  );
}
